### ISSUE TITLE
Проверка лабораторной работы 2 задание 2

### ISSUE THREAD

**Issue by dragoblued** [dragoblued/lab_2_2#1]
Выполнила работу:
Табаева Н.А.

To: @evgeny-p

**Comment by evgeny-p** [comment]
```
*   3955616 (HEAD, origin/master, origin/HEAD, master) Merge branch 'fun'
|\  
| * eaafb5e denotes variables discrimination forgot about that
| * 9e74954 Considered the last case - d > 0
| * d428276 Add the line checking at b=0 c=0 d=0
| * 68a6d30 Disckrimenate case at zero
| * dac98c3 We consider the case for different calues of the discriminant(d>0) and denote variables
| * 98b57c9 We consider the casefor 'a' equal and not equal to zero
* | 33b10db Correct commissioning in main
|/  
* 96530c1 We have changed the type of data
* a2a80ec We crate main function
```

Так выглядит история репозитория. В мастере лишний коммит:
```
* 33b10db Correct commissioning in main
```
Топология повторяет ситуацию, изображенную на [слайде 24](http://evgeny-p.github.io/teaching/materials/week-02/slides/#24).

Для исправления ситуации следовало использовать команду `git rebase`.

В рамках этой работы историю переписывать не нужно, но в будущем следует учесть.

Замечания по коду:

1. Программа компилируется с предупреждениями. При компиляции с ключом `-Wall` предупреждений быть не должно.

1. Хаотичное форматирование кода:
  1. Для отступов используются [табы и пробелы](http://www.emacswiki.org/pics/static/TabsSpacesBoth.png).
  
  1. Перед открывающей круглой скобкой в одних случаях используется пробел, в других — нет. Общее правило: между операторами и открывающей круглой скобкой пробел ставится в соответствии с правилами естественного языка. Определение и вызов функции — математическая запись, в этом случае пробел ставить не принято.

  1. Перед открывающей фигурной скобкой в одних случаях стоит пробел, в других отсутствует. Предпочтительнее ставить.

  1. Тело блока в одних случаях пишется на одной сторке с оператором, в других — с новой строки.

**Comment by dragoblued** [comment]
Я компилировала  - "gcc -o main main.c -lm". Предупреждений не было.

**Comment by evgeny-p** [comment]
Задача закрыта преждевременно. Для сдачи работы нужно исправить замечания по коду. В этом же репозитории.

Исправления форматирования и функциональные изменения нужно оформить как отдельные коммиты.
